/**
 * EHOG v2 TS parity test — reads parity_fixtures.json (generated by test_parity.py)
 * and verifies the TS predictor produces identical results.
 *
 * Run:
 *   python ehog/test_parity.py           # generate fixtures
 *   npx tsx ehog/test_parity.ts          # verify TS matches
 */

import { readFileSync } from 'fs';
import { join } from 'path';
import { rate, rating } from 'openskill';
import { plackettLuce } from 'openskill/models';
import { toEhog, fromEhog, marginMultiplier, predictWinProbability, BETA } from '../src/lib/ehog';
import constants from './constants.json';

const SIGMA_FLOOR = constants.SIGMA_FLOOR;

const TOLERANCE = 1e-8;

interface FixtureResult {
  team: string;
  index: number;
  prior_mu: number;
  prior_sigma: number;
  new_mu: number;
  new_sigma: number;
  prior_ehog: number;
  new_ehog: number;
  delta: number;
}

interface Fixture {
  label: string;
  input: {
    team_a: [number, number][];
    team_b: [number, number][];
    score_a: number;
    score_b: number;
    a_won: boolean;
  };
  margin_multiplier: number;
  results: FixtureResult[];
}

interface EhogInverseFixture {
  label: string;
  target_ehog: number;
  sigma: number;
  mu: number;
  round_trip_ehog: number;
}

interface WinProbFixture {
  label: string;
  team_a: [number, number][];
  team_b: [number, number][];
  p_a: number;
}

interface ParityFixtures {
  match_updates: Fixture[];
  win_prob: WinProbFixture[];
  ehog_inverse: EhogInverseFixture[];
}

/** Wraps a bare (mu, sigma) tuple into the PlayerRating shape predictWinProbability expects. */
function asRating(index: number, [mu, sigma]: [number, number]) {
  return { playerId: index, mu, sigma, ehogRating: 0 };
}

function runFixture(f: Fixture): FixtureResult[] {
  const { team_a, team_b, score_a, score_b, a_won } = f.input;

  const rA = team_a.map(([mu, sigma]) => rating({ mu, sigma }));
  const rB = team_b.map(([mu, sigma]) => rating({ mu, sigma }));
  const [baseA, baseB] = rate([rA, rB], {
    model: plackettLuce,
    beta: BETA,
    rank: a_won ? [0, 1] : [1, 0],
  });

  const m = marginMultiplier(score_a, score_b);
  const results: FixtureResult[] = [];

  for (let i = 0; i < team_a.length; i++) {
    const [priorMu, priorSigma] = team_a[i];
    const newMu = priorMu + m * (baseA[i].mu - priorMu);
    const newSigma = Math.max(SIGMA_FLOOR, baseA[i].sigma);
    const priorEhog = toEhog(priorMu, priorSigma);
    const newEhog = toEhog(newMu, newSigma);
    results.push({
      team: 'A', index: i,
      prior_mu: priorMu, prior_sigma: priorSigma,
      new_mu: newMu, new_sigma: newSigma,
      prior_ehog: priorEhog, new_ehog: newEhog,
      delta: newEhog - priorEhog,
    });
  }
  for (let i = 0; i < team_b.length; i++) {
    const [priorMu, priorSigma] = team_b[i];
    const newMu = priorMu + m * (baseB[i].mu - priorMu);
    const newSigma = Math.max(SIGMA_FLOOR, baseB[i].sigma);
    const priorEhog = toEhog(priorMu, priorSigma);
    const newEhog = toEhog(newMu, newSigma);
    results.push({
      team: 'B', index: i,
      prior_mu: priorMu, prior_sigma: priorSigma,
      new_mu: newMu, new_sigma: newSigma,
      prior_ehog: priorEhog, new_ehog: newEhog,
      delta: newEhog - priorEhog,
    });
  }

  return results;
}

const fixturePath = join(__dirname, 'parity_fixtures.json');
const { match_updates: fixtures, win_prob: winProbFixtures, ehog_inverse: inverseFixtures }: ParityFixtures =
  JSON.parse(readFileSync(fixturePath, 'utf-8'));

let passed = 0;
let failed = 0;

for (const fixture of fixtures) {
  const tsResults = runFixture(fixture);
  const pyResults = fixture.results;

  for (let r = 0; r < pyResults.length; r++) {
    const py = pyResults[r];
    const ts = tsResults[r];

    for (const key of ['new_mu', 'new_sigma', 'new_ehog', 'delta'] as const) {
      const diff = Math.abs(py[key] - ts[key]);
      if (diff > TOLERANCE) {
        console.error(
          `FAIL: "${fixture.label}" ${py.team}${py.index} ${key}: ` +
          `py=${py[key]} ts=${ts[key]} diff=${diff}`
        );
        failed++;
      } else {
        passed++;
      }
    }
  }

  // Also verify margin multiplier
  const tsM = marginMultiplier(fixture.input.score_a, fixture.input.score_b);
  if (Math.abs(tsM - fixture.margin_multiplier) > TOLERANCE) {
    console.error(
      `FAIL: "${fixture.label}" margin_multiplier: py=${fixture.margin_multiplier} ts=${tsM}`
    );
    failed++;
  } else {
    passed++;
  }
}

for (const fixture of winProbFixtures) {
  const teamA = fixture.team_a.map((s, i) => asRating(i, s));
  const teamB = fixture.team_b.map((s, i) => asRating(100 + i, s));
  const tsP = predictWinProbability(teamA, teamB);
  const diff = Math.abs(tsP - fixture.p_a);
  if (diff > TOLERANCE) {
    console.error(`FAIL: win_prob "${fixture.label}": py=${fixture.p_a} ts=${tsP} diff=${diff}`);
    failed++;
  } else {
    passed++;
  }
}

for (const fixture of inverseFixtures) {
  const tsMu = fromEhog(fixture.target_ehog, fixture.sigma);
  const diff = Math.abs(tsMu - fixture.mu);
  if (diff > TOLERANCE) {
    console.error(`FAIL: ehog_inverse "${fixture.label}" mu: py=${fixture.mu} ts=${tsMu} diff=${diff}`);
    failed++;
  } else {
    passed++;
  }
}

console.log(`\n${passed} checks passed, ${failed} failed.`);
if (failed > 0) process.exit(1);
else console.log('Parity test PASSED.');
