-- Local/CI baseline data: `supabase start` and the E2E workflow both run this after migrations
-- (see docs/e2e.md). Player ids 1 and 7 are load-bearing — `authOptions.js`'s dev-mode mock
-- providers (`dev-zach-mock`/`dev-dan-mock`) hardcode `devPlayerId: 1`/`7`, so the dev-login
-- dropdown (`TopbarShell.tsx`'s `DevToggle`) only resolves to a real player when those exact ids
-- exist. `players.id` is `generated by default as identity`, so explicit ids are allowed here.

insert into players (id, name, is_admin) values
  (1, 'Zach', true),
  (2, 'Casey', false),
  (3, 'Drew', false),
  (4, 'Sam', false),
  (5, 'Jordan', false),
  (6, 'Riley', false),
  (7, 'Dan', false);
select setval(pg_get_serial_sequence('players', 'id'), (select max(id) from players));

insert into maps (name, slug) values
  ('foroglio', 'foroglio'),
  ('ganny', 'ganny'),
  ('memento', 'memento'),
  ('palais', 'palais'),
  ('rooftop', 'rooftop');
