-- Post-season survey (#113) and player-voted superlatives. Both hang off a regular season and are
-- opened/closed by an admin; only players who played in the season (or its paired gauntlet) may
-- respond, once each, and can edit their answers while the form is open.
--
-- Anonymity: `survey_responses.player_id` / `superlative_votes.voter_player_id` exist only to
-- enforce one-response-per-player and to prefill the editor for that same player. No read path that
-- feeds the admin results view selects them.

-- ── Survey ──────────────────────────────────────────────────────────────────────────────────────

create table public.surveys (
  id integer primary key generated by default as identity,
  season_id integer not null unique,
  opened_at timestamptz not null default now(),
  closed_at timestamptz
);

-- A survey's questions are a snapshot taken when it is created: the custom ones the admin typed
-- followed by the core ones (`is_core`), so a survey's results stay readable no matter how the core
-- list evolves afterward. `kind` decides the answer shape: `rating` is 1-5, `yes_no` is 0/1 (both
-- stored in `survey_answers.answer_number`), `text` is free text (`answer_text`).
create table public.survey_questions (
  id integer primary key generated by default as identity,
  survey_id integer not null,
  position integer not null,
  kind text not null check (kind in ('rating', 'yes_no', 'text')),
  prompt text not null,
  is_core boolean not null default false,
  unique (survey_id, position)
);

create table public.survey_responses (
  id integer primary key generated by default as identity,
  survey_id integer not null,
  player_id integer not null,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (survey_id, player_id)
);

create table public.survey_answers (
  id integer primary key generated by default as identity,
  response_id integer not null,
  question_id integer not null,
  answer_number smallint,
  answer_text text,
  unique (response_id, question_id)
);

alter table public.surveys
  add constraint surveys_season_id_fkey foreign key (season_id) references public.seasons(id) on delete cascade;
alter table public.survey_questions
  add constraint survey_questions_survey_id_fkey foreign key (survey_id) references public.surveys(id) on delete cascade;
alter table public.survey_responses
  add constraint survey_responses_survey_id_fkey foreign key (survey_id) references public.surveys(id) on delete cascade;
alter table public.survey_responses
  add constraint survey_responses_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;
alter table public.survey_answers
  add constraint survey_answers_response_id_fkey foreign key (response_id) references public.survey_responses(id) on delete cascade;
alter table public.survey_answers
  add constraint survey_answers_question_id_fkey foreign key (question_id) references public.survey_questions(id) on delete cascade;

create index survey_responses_survey_id_idx on public.survey_responses using btree (survey_id);
create index survey_answers_question_id_idx on public.survey_answers using btree (question_id);

-- ── Superlatives ────────────────────────────────────────────────────────────────────────────────

-- One row per season whose superlatives vote has been set up. The admin builds the superlative list
-- while `is_open` is false; players only see the ballot once it is open.
create table public.superlative_polls (
  season_id integer primary key,
  is_open boolean not null default false
);

-- The superlatives an admin chose for a season ("Best Teammate", "Clutch King", …). Every
-- participant of the season is a valid nominee for every superlative.
create table public.superlatives (
  id integer primary key generated by default as identity,
  season_id integer not null,
  position integer not null,
  title text not null,
  unique (season_id, position)
);

create table public.superlative_votes (
  id integer primary key generated by default as identity,
  superlative_id integer not null,
  voter_player_id integer not null,
  nominee_player_id integer not null,
  voted_at timestamptz not null default now(),
  unique (superlative_id, voter_player_id)
);

alter table public.superlative_polls
  add constraint superlative_polls_season_id_fkey foreign key (season_id) references public.seasons(id) on delete cascade;
alter table public.superlatives
  add constraint superlatives_season_id_fkey foreign key (season_id) references public.seasons(id) on delete cascade;
alter table public.superlative_votes
  add constraint superlative_votes_superlative_id_fkey foreign key (superlative_id) references public.superlatives(id) on delete cascade;
alter table public.superlative_votes
  add constraint superlative_votes_voter_player_id_fkey foreign key (voter_player_id) references public.players(id) on delete cascade;
alter table public.superlative_votes
  add constraint superlative_votes_nominee_player_id_fkey foreign key (nominee_player_id) references public.players(id) on delete cascade;

create index superlatives_season_id_idx on public.superlatives using btree (season_id);
create index superlative_votes_superlative_id_idx on public.superlative_votes using btree (superlative_id);
