-- Reconstructed from the live production schema via pg_catalog introspection (no supabase/
-- directory existed before this — the 19 migrations applied to production were never tracked as
-- local files). This single file is the baseline `supabase start`/CI replays from; see docs/e2e.md
-- for why local Postgres, not a Supabase branch, is this repo's isolation strategy.

-- ─── Enum types ────────────────────────────────────────────────────────────────

create type public.faction_side_type as enum ('SHIRTS', 'SKINS');
create type public.season_status_type as enum ('ARCHIVED', 'ACTIVE', 'UPCOMING');

-- ─── Tables ─────────────────────────────────────────────────────────────────────

create table public.players (
  id integer primary key generated by default as identity,
  name text not null,
  discord_id text,
  steam_id text,
  steam_avatar_url text,
  steam_nickname text,
  is_admin boolean not null default false,
  steam_refreshed_at timestamptz,
  seed_ehog numeric check (seed_ehog is null or (seed_ehog > 10 and seed_ehog < 100)),
  name_changed_at timestamptz,
  discord_name_role_id text,
  unique (discord_id),
  unique (name),
  unique (steam_id)
);
create unique index players_name_lower_unique on public.players using btree (lower(name));

create table public.maps (
  id integer primary key generated by default as identity,
  name text not null unique,
  slug text not null unique,
  workshop_url text,
  image_url text,
  radar_image_url text,
  radar_pos_x real,
  radar_pos_y real,
  radar_scale real,
  radar_source text check (radar_source is null or radar_source = any (array['vpk', 'auto', 'manual']))
);

create table public.seasons (
  id integer primary key generated by default as identity,
  name text not null unique,
  status public.season_status_type not null default 'UPCOMING',
  target_win_rounds integer not null default 13,
  buy_in_amount numeric(5, 2) default 10.00,
  is_gauntlet boolean not null default false,
  start_date date,
  map_pool text[],
  schedule_draft_locked_at timestamptz
);

create table public.weeks (
  id integer primary key generated by default as identity,
  season_id integer,
  week_number integer not null,
  bye_player_id integer,
  unique (season_id, week_number)
);

create table public.matches (
  id integer primary key generated by default as identity,
  week_id integer,
  match_number integer not null,
  final_score text,
  picked_map text,
  shirts_ban text,
  skins_ban1 text,
  skins_ban2 text,
  shirts_pick text,
  skins_starting_side text,
  is_playoff_game boolean default false,
  shirts_ban2 text,
  scheduled_at timestamptz,
  is_feature_match boolean not null default false,
  recording_url text,
  round_history jsonb,
  replay_status text not null default 'none'
    check (replay_status = any (array['none', 'queued', 'running', 'ready', 'failed'])),
  pre_match_win_prob numeric check (pre_match_win_prob is null or (pre_match_win_prob >= 0 and pre_match_win_prob <= 1)),
  pre_match_win_prob_formula_version text
);
create index matches_week_id_idx on public.matches using btree (week_id);

create table public.player_match_stats (
  id integer primary key generated by default as identity,
  match_id integer,
  player_id integer,
  faction public.faction_side_type not null,
  kills integer not null default 0,
  assists integer not null default 0,
  deaths integer not null default 0,
  adr integer not null default 0,
  damage integer not null default 0,
  rounds_played integer not null default 0,
  rounds_won integer not null default 0,
  is_win boolean not null default false,
  unique (match_id, player_id)
);
create index player_match_stats_player_id_idx on public.player_match_stats using btree (player_id);

create table public.player_match_sabremetrics (
  player_match_stats_id integer primary key,
  kills_ct integer not null default 0,
  kills_t integer not null default 0,
  deaths_ct integer not null default 0,
  deaths_t integer not null default 0,
  assists_ct integer not null default 0,
  assists_t integer not null default 0,
  damage_ct integer not null default 0,
  damage_t integer not null default 0,
  headshot_kills integer not null default 0,
  headshot_kills_ct integer not null default 0,
  headshot_kills_t integer not null default 0,
  opening_kills integer not null default 0,
  opening_deaths integer not null default 0,
  kast_rounds integer not null default 0,
  clutch_1v1_attempts integer not null default 0,
  clutch_1v1_wins integer not null default 0,
  clutch_1v2_attempts integer not null default 0,
  clutch_1v2_wins integer not null default 0,
  flash_assists integer not null default 0,
  utility_damage integer not null default 0,
  blind_duration_dealt real not null default 0,
  enemies_flashed integer not null default 0,
  flashes_thrown integer not null default 0,
  teamflash_duration real not null default 0,
  plants integer not null default 0,
  defuses integer not null default 0,
  two_k_rounds integer not null default 0,
  flashes_leading_to_kill integer not null default 0,
  blind_duration_max_sum numeric not null default 0,
  effective_flashes integer not null default 0,
  trade_kill_opportunities integer not null default 0,
  trade_kill_attempts integer not null default 0,
  trade_kill_successes integer not null default 0,
  traded_death_opportunities integer not null default 0,
  traded_death_attempts integer not null default 0,
  traded_death_successes integer not null default 0,
  he_thrown integer not null default 0,
  he_damage integer not null default 0,
  unused_util_value_on_death_total integer not null default 0,
  counter_strafe_shots integer not null default 0,
  counter_strafe_good_shots integer not null default 0,
  spray_shots_fired integer not null default 0,
  spray_shots_hit integer not null default 0,
  shots_fired integer not null default 0,
  shots_hit integer not null default 0,
  headshot_hits integer not null default 0,
  smokes_blocking_push integer not null default 0,
  shots_hit_no_awp integer not null default 0,
  headshot_hits_no_awp integer not null default 0,
  ct_smokes_thrown integer not null default 0,
  clutch_2v1_attempts integer not null default 0,
  clutch_2v1_wins integer not null default 0,
  teamkills integer not null default 0,
  rounds_dropped_on_reload_total integer not null default 0,
  reloads_total integer not null default 0
);

create table public.player_match_weapon_stats (
  id bigint primary key generated always as identity,
  player_match_stats_id bigint not null,
  weapon_category text not null,
  shots_fired integer not null default 0,
  shots_hit integer not null default 0,
  headshot_hits integer not null default 0,
  damage_dealt integer not null default 0,
  rounds_played integer not null default 0,
  unique (player_match_stats_id, weapon_category)
);

create table public.player_match_economy_stats (
  id bigint primary key generated always as identity,
  player_match_stats_id bigint not null,
  economy_type text not null,
  shots_fired integer not null default 0,
  shots_hit integer not null default 0,
  headshot_hits integer not null default 0,
  damage_dealt integer not null default 0,
  rounds_played integer not null default 0,
  unique (player_match_stats_id, economy_type)
);

create table public.player_current_ratings (
  player_id bigint primary key,
  ehog_v1 double precision,
  updated_at timestamptz not null default now()
);

create table public.player_rating_history (
  id bigint primary key generated always as identity,
  player_id bigint not null,
  match_id bigint not null,
  formula_version text not null default 'ehog_v1',
  sequence_index integer not null,
  skill_rating_weight double precision not null default 1.0,
  mu double precision not null,
  sigma double precision not null,
  ehog_rating double precision not null,
  rating_delta double precision not null default 0,
  computed_at timestamptz not null default now(),
  unique (player_id, match_id, formula_version)
);
create index player_rating_history_match_idx on public.player_rating_history using btree (match_id);
create index player_rating_history_player_idx on public.player_rating_history using btree (player_id);
create index player_rating_history_player_version_seq_idx on public.player_rating_history using btree (player_id, formula_version, sequence_index);

create table public.player_name_history (
  id bigint primary key generated always as identity,
  player_id bigint not null,
  old_name text not null,
  new_name text not null,
  changed_at timestamptz not null default now()
);
create index player_name_history_player_id_changed_at_idx on public.player_name_history using btree (player_id, changed_at desc);

create table public.season_players (
  id integer primary key generated by default as identity,
  season_id integer not null,
  player_id integer not null,
  joined_at timestamptz not null default now(),
  unique (season_id, player_id)
);

create table public.season_schedule_draft_weeks (
  id integer primary key generated by default as identity,
  season_id integer not null,
  week_number integer not null,
  bye_player_id integer,
  unique (season_id, week_number)
);

create table public.season_schedule_draft_matches (
  id integer primary key generated by default as identity,
  draft_week_id integer not null,
  match_number integer not null,
  shirts_player1_id integer not null,
  shirts_player2_id integer not null,
  skins_player1_id integer not null,
  skins_player2_id integer not null,
  unique (draft_week_id, match_number)
);

create table public.gauntlet_pods (
  id integer primary key generated by default as identity,
  season_id integer not null,
  round_number integer not null,
  pod_index integer not null,
  advance_rule text not null check (advance_rule = any (array['single', 'wildcard'])),
  is_final boolean not null default false,
  week_id integer,
  match1_id integer,
  match2_id integer,
  unique (season_id, round_number, pod_index)
);

create table public.gauntlet_pod_slots (
  id integer primary key generated by default as identity,
  pod_id integer not null,
  slot_index integer not null check (slot_index >= 0 and slot_index <= 3),
  source_kind text not null check (source_kind = any (array['seed', 'pod'])),
  source_seed integer,
  source_pod_id integer,
  player_id integer,
  unique (pod_id, slot_index),
  check (source_kind <> 'seed' or player_id is null or source_seed is not null)
);

create table public.live_match_score (
  match_id integer primary key,
  shirts_score integer not null,
  skins_score integer not null,
  round integer,
  updated_at timestamptz not null default now()
);

create table public.match_discord_state (
  match_id bigint primary key,
  reminder_sent_at timestamptz,
  thread_id text,
  notification_message_id text,
  event_id text,
  message_checkpoint text
);

create table public.match_server_state (
  match_id integer primary key,
  server_state text not null default 'idle'
    check (server_state = any (array['idle', 'provisioning', 'live', 'tearing_down', 'done', 'failed'])),
  dathost_server_id text,
  connect_string text,
  server_started_at timestamptz,
  teardown_at timestamptz
);

create table public.background_jobs (
  id bigint primary key generated always as identity,
  job_type text not null,
  match_id integer,
  map_id integer,
  status text not null default 'queued',
  stage text,
  error_message text,
  gh_run_id bigint,
  gh_run_url text,
  requested_by integer,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz not null default now()
);
create unique index background_jobs_type_map_uniq on public.background_jobs using btree (job_type, map_id);
create unique index background_jobs_type_match_uniq on public.background_jobs using btree (job_type, match_id);

create table public.ops_errors (
  id integer primary key generated by default as identity,
  entity_type text not null check (entity_type = any (array['season', 'match', 'player', 'system'])),
  entity_id integer not null default 0,
  operation text not null,
  message text not null,
  occurred_at timestamptz not null default now(),
  dismissed_at timestamptz,
  unique (entity_type, entity_id, operation)
);

create table public.config_sets (
  id integer primary key generated by default as identity,
  key text not null unique,
  label text not null,
  server_settings jsonb not null default '{}'::jsonb,
  cs2_settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.config_set_files (
  id integer primary key generated by default as identity,
  config_set_id integer not null,
  remote_path text not null,
  content text not null,
  unique (config_set_id, remote_path)
);

create table public.scrim_sessions (
  id smallint primary key default 1 check (id = 1),
  started_by integer not null,
  warned_15 boolean not null default false,
  warned_10 boolean not null default false,
  warned_5 boolean not null default false
);

-- ─── Foreign keys (added after every table exists, so creation order above never has to
--     satisfy forward references) ──────────────────────────────────────────────────────

alter table public.weeks
  add constraint weeks_season_id_fkey foreign key (season_id) references public.seasons(id) on delete cascade,
  add constraint weeks_bye_player_id_fkey foreign key (bye_player_id) references public.players(id) on delete set null;

alter table public.matches
  add constraint matches_week_id_fkey foreign key (week_id) references public.weeks(id) on delete cascade;

alter table public.player_match_stats
  add constraint player_match_stats_match_id_fkey foreign key (match_id) references public.matches(id) on delete cascade,
  add constraint player_match_stats_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;

alter table public.player_match_sabremetrics
  add constraint player_match_sabremetrics_player_match_stats_id_fkey foreign key (player_match_stats_id) references public.player_match_stats(id) on delete cascade;

alter table public.player_match_weapon_stats
  add constraint player_match_weapon_stats_player_match_stats_id_fkey foreign key (player_match_stats_id) references public.player_match_stats(id) on delete cascade;

alter table public.player_match_economy_stats
  add constraint player_match_economy_stats_player_match_stats_id_fkey foreign key (player_match_stats_id) references public.player_match_stats(id) on delete cascade;

alter table public.player_current_ratings
  add constraint player_current_ratings_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;

alter table public.player_rating_history
  add constraint player_rating_history_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade,
  add constraint player_rating_history_match_id_fkey foreign key (match_id) references public.matches(id) on delete cascade;

alter table public.player_name_history
  add constraint player_name_history_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;

alter table public.season_players
  add constraint season_players_season_id_fkey foreign key (season_id) references public.seasons(id),
  add constraint season_players_player_id_fkey foreign key (player_id) references public.players(id);

alter table public.season_schedule_draft_weeks
  add constraint season_schedule_draft_weeks_season_id_fkey foreign key (season_id) references public.seasons(id),
  add constraint season_schedule_draft_weeks_bye_player_id_fkey foreign key (bye_player_id) references public.players(id);

alter table public.season_schedule_draft_matches
  add constraint season_schedule_draft_matches_draft_week_id_fkey foreign key (draft_week_id) references public.season_schedule_draft_weeks(id),
  add constraint season_schedule_draft_matches_shirts_player1_id_fkey foreign key (shirts_player1_id) references public.players(id),
  add constraint season_schedule_draft_matches_shirts_player2_id_fkey foreign key (shirts_player2_id) references public.players(id),
  add constraint season_schedule_draft_matches_skins_player1_id_fkey foreign key (skins_player1_id) references public.players(id),
  add constraint season_schedule_draft_matches_skins_player2_id_fkey foreign key (skins_player2_id) references public.players(id);

alter table public.gauntlet_pods
  add constraint gauntlet_pods_season_id_fkey foreign key (season_id) references public.seasons(id) on delete cascade,
  add constraint gauntlet_pods_week_id_fkey foreign key (week_id) references public.weeks(id),
  add constraint gauntlet_pods_match1_id_fkey foreign key (match1_id) references public.matches(id),
  add constraint gauntlet_pods_match2_id_fkey foreign key (match2_id) references public.matches(id);

alter table public.gauntlet_pod_slots
  add constraint gauntlet_pod_slots_pod_id_fkey foreign key (pod_id) references public.gauntlet_pods(id) on delete cascade,
  add constraint gauntlet_pod_slots_source_pod_id_fkey foreign key (source_pod_id) references public.gauntlet_pods(id),
  add constraint gauntlet_pod_slots_player_id_fkey foreign key (player_id) references public.players(id);

alter table public.live_match_score
  add constraint live_match_score_match_id_fkey foreign key (match_id) references public.matches(id) on delete cascade;

alter table public.match_discord_state
  add constraint match_discord_state_match_id_fkey foreign key (match_id) references public.matches(id) on delete cascade;

alter table public.match_server_state
  add constraint match_server_state_match_id_fkey foreign key (match_id) references public.matches(id) on delete cascade;

alter table public.background_jobs
  add constraint background_jobs_match_id_fkey foreign key (match_id) references public.matches(id) on delete cascade,
  add constraint background_jobs_map_id_fkey foreign key (map_id) references public.maps(id) on delete cascade,
  add constraint background_jobs_requested_by_fkey foreign key (requested_by) references public.players(id);

alter table public.config_set_files
  add constraint config_set_files_config_set_id_fkey foreign key (config_set_id) references public.config_sets(id) on delete cascade;

alter table public.scrim_sessions
  add constraint scrim_sessions_started_by_fkey foreign key (started_by) references public.players(id);

-- ─── View ───────────────────────────────────────────────────────────────────────

create view public.player_season_leaderboard as
select
  w.season_id,
  p.id as player_id,
  p.name as player_name,
  count(pms.id) as matches_played,
  sum(case when pms.is_win = true then 1 else 0 end) as matches_won,
  sum(case when pms.is_win = false then 1 else 0 end) as matches_lost,
  round(((sum(case when pms.is_win = true then 1.0 else 0.0 end) / count(pms.id)::numeric) * 100::numeric), 2) as win_rate_percentage,
  sum(pms.kills) as total_kills,
  sum(pms.deaths) as total_deaths,
  round((sum(pms.kills)::numeric / nullif(sum(pms.deaths), 0)::numeric), 2) as kd_ratio,
  sum(pms.damage) as total_damage,
  sum(pms.rounds_played) as total_rounds_played,
  (sum(pms.damage)::numeric / nullif(sum(pms.rounds_played), 0)::numeric) as overall_adr
from public.player_match_stats pms
  join public.players p on pms.player_id = p.id
  join public.matches m on pms.match_id = m.id
  join public.weeks w on m.week_id = w.id
where m.is_playoff_game = false
  and m.final_score is not null
  and m.final_score !~ '^\s*0\s*[-–]\s*0\s*$'
group by w.season_id, p.id, p.name;

-- ─── Functions + trigger ────────────────────────────────────────────────────────

create or replace function public.enforce_season_players_upcoming()
returns trigger
language plpgsql
as $function$
declare
  v_status season_status_type;
  v_season_id integer;
begin
  v_season_id := coalesce(new.season_id, old.season_id);
  select status into v_status from public.seasons where id = v_season_id for update;
  if v_status is distinct from 'UPCOMING' then
    raise exception 'Roster can only be edited while the season is UPCOMING';
  end if;
  return coalesce(new, old);
end;
$function$;

create trigger season_players_upcoming_only
  before insert or delete on public.season_players
  for each row execute function public.enforce_season_players_upcoming();

-- Reconciles a gauntlet bracket-editor save (delete/insert/update pods + a full slot rewrite) in one
-- transaction — see GauntletPodEditor.tsx / gauntlet-engine.ts for the caller.
create or replace function public.reconcile_gauntlet_draft(
  p_delete_pod_ids integer[],
  p_new_pods jsonb,
  p_updated_pods jsonb,
  p_slot_rewrite_pod_ids integer[],
  p_slots jsonb
)
returns jsonb
language plpgsql
as $function$
declare
  key_map jsonb := '{}'::jsonb;
  new_pod jsonb;
  new_id integer;
  upd jsonb;
  slot jsonb;
  resolved_pod_id integer;
  resolved_source_pod_id integer;
  skipped_ids integer[];
begin
  -- Snapshot, in this same transaction, which of the touched already-persisted pods have
  -- materialized (match1_id set) since the caller last read the shape — a concurrent match score
  -- landing via resolveAndPropagate() between that read and this call must not be clobbered.
  -- Deletion/update/rewrite/insertion below all skip anything in this set.
  select coalesce(array_agg(id), '{}') into skipped_ids
  from gauntlet_pods
  where id = any(coalesce(p_delete_pod_ids, '{}') || coalesce(p_slot_rewrite_pod_ids, '{}'))
    and match1_id is not null;

  delete from gauntlet_pod_slots
  where pod_id = any(coalesce(p_delete_pod_ids, '{}'))
    and pod_id != all(skipped_ids);
  delete from gauntlet_pods
  where id = any(coalesce(p_delete_pod_ids, '{}'))
    and id != all(skipped_ids);

  for new_pod in select * from jsonb_array_elements(coalesce(p_new_pods, '[]'::jsonb))
  loop
    insert into gauntlet_pods (season_id, round_number, pod_index, advance_rule, is_final)
    values (
      (new_pod->>'season_id')::integer,
      (new_pod->>'round_number')::integer,
      (new_pod->>'pod_index')::integer,
      new_pod->>'advance_rule',
      (new_pod->>'is_final')::boolean
    )
    returning id into new_id;
    key_map := key_map || jsonb_build_object(new_pod->>'temp_key', new_id);
  end loop;

  for upd in select * from jsonb_array_elements(coalesce(p_updated_pods, '[]'::jsonb))
  loop
    update gauntlet_pods
    set advance_rule = upd->>'advance_rule',
        is_final = (upd->>'is_final')::boolean
    where id = (upd->>'id')::integer
      and id != all(skipped_ids);
  end loop;

  delete from gauntlet_pod_slots
  where pod_id = any(coalesce(p_slot_rewrite_pod_ids, '{}'))
    and pod_id != all(skipped_ids);

  for slot in select * from jsonb_array_elements(coalesce(p_slots, '[]'::jsonb))
  loop
    resolved_pod_id := case
      when slot->'pod_ref'->>'kind' = 'id' then (slot->'pod_ref'->>'value')::integer
      else (key_map->>(slot->'pod_ref'->>'value'))::integer
    end;
    continue when resolved_pod_id = any(skipped_ids);
    resolved_source_pod_id := case
      when slot->'source_pod_ref' is null then null
      when slot->'source_pod_ref'->>'kind' = 'id' then (slot->'source_pod_ref'->>'value')::integer
      else (key_map->>(slot->'source_pod_ref'->>'value'))::integer
    end;
    insert into gauntlet_pod_slots (pod_id, slot_index, source_kind, source_seed, source_pod_id, player_id)
    values (
      resolved_pod_id,
      (slot->>'slot_index')::integer,
      slot->>'source_kind',
      (slot->>'source_seed')::integer,
      resolved_source_pod_id,
      (slot->>'player_id')::integer
    );
  end loop;

  return jsonb_build_object('key_map', key_map, 'skipped_pod_ids', to_jsonb(skipped_ids));
end;
$function$;
