-- Post-season survey (#113) and player-voted superlatives. Both hang off a regular season and are
-- opened/closed by an admin; only players who played in the season (or its paired gauntlet) may
-- respond, once each, and can edit their answers while the form is open.
--
-- `survey_responses.player_id` / `superlative_votes.voter_player_id` exist to enforce
-- one-submission-per-player and to prefill that same player's editor. No results query selects them.

-- ── Survey ──────────────────────────────────────────────────────────────────────────────────────

-- `questions` is a snapshot taken when the survey is sent: an array of
-- `{ id, kind, prompt, is_core }` (the admin's custom questions, then the core ones), `id` being the
-- 1-based position and `kind` one of 'rating' (1-5), 'yes_no', 'text'. Snapshotting keeps a past
-- survey's results readable however the core list later changes. `closed_at` null means open.
create table public.surveys (
  id integer primary key generated by default as identity,
  season_id integer not null unique,
  questions jsonb not null,
  closed_at timestamptz
);

-- `answers` is one object per response keyed by question id: a number for a rating, a boolean for
-- yes/no, a string for text; an unanswered question has no key. Saving a response is one upsert.
create table public.survey_responses (
  id integer primary key generated by default as identity,
  survey_id integer not null,
  player_id integer not null,
  answers jsonb not null default '{}'::jsonb,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (survey_id, player_id)
);

alter table public.surveys
  add constraint surveys_season_id_fkey foreign key (season_id) references public.seasons(id) on delete cascade;
alter table public.survey_responses
  add constraint survey_responses_survey_id_fkey foreign key (survey_id) references public.surveys(id) on delete cascade;
alter table public.survey_responses
  add constraint survey_responses_player_id_fkey foreign key (player_id) references public.players(id) on delete cascade;

-- ── Superlatives ────────────────────────────────────────────────────────────────────────────────

-- One row per season whose superlatives vote has been set up. The admin builds the superlative list
-- while `is_open` is false; players only see the ballot once it is open.
create table public.superlative_polls (
  season_id integer primary key,
  is_open boolean not null default false
);

-- The superlatives an admin chose for a season ("Best Teammate", "Clutch King", …). Every player
-- who played the season is a valid nominee for every superlative.
create table public.superlatives (
  id integer primary key generated by default as identity,
  season_id integer not null,
  position integer not null,
  title text not null,
  unique (season_id, position)
);

create table public.superlative_votes (
  id integer primary key generated by default as identity,
  superlative_id integer not null,
  voter_player_id integer not null,
  nominee_player_id integer not null,
  unique (superlative_id, voter_player_id)
);

alter table public.superlative_polls
  add constraint superlative_polls_season_id_fkey foreign key (season_id) references public.seasons(id) on delete cascade;
alter table public.superlatives
  add constraint superlatives_season_id_fkey foreign key (season_id) references public.seasons(id) on delete cascade;
alter table public.superlative_votes
  add constraint superlative_votes_superlative_id_fkey foreign key (superlative_id) references public.superlatives(id) on delete cascade;
alter table public.superlative_votes
  add constraint superlative_votes_voter_player_id_fkey foreign key (voter_player_id) references public.players(id) on delete cascade;
alter table public.superlative_votes
  add constraint superlative_votes_nominee_player_id_fkey foreign key (nominee_player_id) references public.players(id) on delete cascade;
